name: Release Zip
on:
  push:
    tags:
      - "v*.*.*"
jobs:
    make-zip:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Make a file
          shell: bash
          run: |
            7z a bingo-${{ github.ref_name }}.zip bingo.py bingo.inx README.md LICENSE samples/ preview/
        - name: Upload Bingo zip
          uses: actions/upload-artifact@v3
          with:
            name: upload zip
            path: bingo-${{ github.ref_name }}.zip
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: bingo-${{ github.ref_name }}.zip
